version: '3.8'

services:
  news-api:
    build:
      context: ..   # Go up one directory to the project root
      dockerfile: docker/news-api/Dockerfile
    container_name: news-api-service
    environment:
      - DEBUG=True
      - ELASTICSEARCH_URL=http://news-elasticsearch:9200
      - NEWS_INDEX=news
      - ENABLE_NEWS_SCRAPER=False # Disable scraper in the API service
      # Claude API settings
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_API_URL=${CLAUDE_API_URL:-https://api.anthropic.com/v1/messages}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3-5-haiku-20241022}
      - ENABLE_AUTO_SUMMARIZATION=${ENABLE_AUTO_SUMMARIZATION:-False}
      - SUMMARY_MAX_LENGTH=${SUMMARY_MAX_LENGTH:-150}
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
      - ../nltk_data:/app/nltk_data
    networks:
      - news-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  news-network:
    external: true
    name: news-network