version: '3.8'

services:
  data-populator:
    build:
      context: ..  # Go up one directory to the project root
      dockerfile: docker/data-populator/Dockerfile
    container_name: news-data-populator
    environment:
      - ELASTICSEARCH_URL=http://news-elasticsearch:9200
      - NEWS_INDEX=news
      - SCRAPER_INTERVAL_MINUTES=5
      - SCRAPER_VERIFY_SSL=True
      # Claude API settings
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_API_URL=${CLAUDE_API_URL:-https://api.anthropic.com/v1/messages}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3-5-haiku-20241022}
      - ENABLE_AUTO_SUMMARIZATION=${ENABLE_AUTO_SUMMARIZATION:-True}
      - SUMMARY_MAX_LENGTH=${SUMMARY_MAX_LENGTH:-150}
      # Event Service settings
      - EVENT_API_BASE_URL=${EVENT_API_BASE_URL:-https://api.in.webengage.com}
      - EVENT_ACCOUNT_ID=${EVENT_ACCOUNT_ID}
      - EVENT_LICENSE_CODE=${EVENT_LICENSE_CODE}
      
    volumes:
      - ..:/app
      - ../nltk_data:/app/nltk_data
    networks:
      - news-network
    restart: unless-stopped

networks:
  news-network:
    external: true
    name: news-network